### ISSUE TITLE
Training of ISL Sign Language Recognition 

### ISSUE THREAD

**Issue by pranjalkar99** [pranjalkar99/shruti-drishti#5]
Failing!! 

CUDA out of memory !

**Comment by bhaswata08** [comment]
Where did you train?

**Comment by pranjalkar99** [comment]
Local GPU failing,, moving to server, continue training on Kaggle for backup as well

**Comment by pranjalkar99** [comment]
Refactored to [#9](https://github.com/pranjalkar99/shruti-drishti/issues/9)
